### ISSUE TITLE
Canvas Resizing Issue

### ISSUE THREAD

**Issue by umanda** [scenify/scenify-sdk#38]
Canvas Re-Sizing not work as expected

1. Open editor https://editor.scenify.dev/
2. Add an Object
3. Resize canvas

![image](https://user-images.githubusercontent.com/368338/145342356-9274692a-d7b3-45ed-8fc7-a15d3984ddf5.png)

**Comment by xorb** [comment]
It should be fixed in 0.3.0. Design editor needs to update SDK version

**Comment by xorb** [comment]
Updated SDK version for design editor. It should be fixed now.
